import { useEffect, useState } from "react";
import { ArrowLeft, Check, Loader2, Settings2, UserRound } from "lucide-react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";

export default function SettingsPage() {
  const { user, loading, isAuthenticated } = useAuth();
  const profile = trpc.account.profile.useQuery(undefined, { enabled: isAuthenticated, retry: false });
  const utils = trpc.useUtils();
  const update = trpc.account.updateProfile.useMutation({ onSuccess: () => utils.account.profile.invalidate() });
  const [name, setName] = useState("");
  const [avatarUrl, setAvatarUrl] = useState("");
  const [preferences, setPreferences] = useState({ dailyGoal: "20", pace: "steady", reminders: true });
  useEffect(() => { const data = profile.data; if (!data) return; setName(data.name ?? user?.name ?? ""); setAvatarUrl(data.avatarUrl ?? ""); if (data.studyPreferences) { try { setPreferences((current) => ({ ...current, ...JSON.parse(data.studyPreferences!) })); } catch { /* keep defaults for older records */ } } }, [profile.data, user?.name]);
  if (loading) return <main className="settings-page settings-page--center"><Loader2 className="spin" size={20} /> Opening your account desk…</main>;
  if (!isAuthenticated) return <main className="settings-page settings-page--center"><section className="settings-card settings-card--narrow"><UserRound size={28} /><h1>Sign in to shape your desk.</h1><p>Your profile and study preferences are private to your account.</p><button className="button button--dark" onClick={() => startLogin()}>Sign in <ArrowLeft size={15} /></button></section></main>;
  return <main className="settings-page"><header className="settings-header"><div><span className="settings-kicker"><Settings2 size={14} /> Account settings</span><h1>Make the desk<br /><em>feel like yours.</em></h1><p>Small choices that make returning to study easier.</p></div><Link href="/" className="button button--light"><ArrowLeft size={15} /> Back to workspace</Link></header><form className="settings-card" onSubmit={(event) => { event.preventDefault(); update.mutate({ name: name.trim(), avatarUrl: avatarUrl.trim() ? avatarUrl.trim() : null, studyPreferences: JSON.stringify(preferences) }); }}><section className="settings-section"><div><span className="settings-kicker">Profile</span><h2>Your identity at the desk.</h2><p>This is how Mochi greets you across your private workspace.</p></div><div className="profile-form"><div className="profile-avatar">{avatarUrl ? <img src={avatarUrl} alt="" /> : <span>{(name || "M").slice(0, 1).toUpperCase()}</span>}</div><label>Display name<input value={name} onChange={(event) => setName(event.target.value)} maxLength={120} required /></label><label>Avatar image URL<span className="field-note">Optional HTTPS image address</span><input value={avatarUrl} onChange={(event) => setAvatarUrl(event.target.value)} placeholder="https://…" type="url" /></label></div></section><section className="settings-section"><div><span className="settings-kicker">Study preferences</span><h2>Set your natural rhythm.</h2><p>These preferences guide your study prompts; they never affect your access or role.</p></div><div className="preference-grid"><label>Daily card goal<select value={preferences.dailyGoal} onChange={(event) => setPreferences({ ...preferences, dailyGoal: event.target.value })}><option value="10">10 cards</option><option value="20">20 cards</option><option value="40">40 cards</option><option value="60">60 cards</option></select></label><label>Study pace<select value={preferences.pace} onChange={(event) => setPreferences({ ...preferences, pace: event.target.value })}><option value="gentle">Gentle</option><option value="steady">Steady</option><option value="deep">Deep focus</option></select></label><label className="preference-toggle"><input type="checkbox" checked={preferences.reminders} onChange={(event) => setPreferences({ ...preferences, reminders: event.target.checked })} /><span><strong>Gentle reminders</strong><small>Keep your next good hour visible.</small></span></label></div></section><div className="settings-actions"><span>{update.isSuccess && <><Check size={14} /> Saved to your account</>}</span><button className="button button--dark" disabled={update.isPending}>{update.isPending ? <><Loader2 className="spin" size={15} /> Saving…</> : "Save preferences"}</button></div>{update.error && <p className="settings-error">{update.error.message}</p>}</form></main>;
}
